FORMAT: 1A
HOST: TODO

# Sir Octopus API
API specification used for communication between server and Android client.

## Tasks [/tasks]
### List all Tasks [GET]
+ Response 200 (application/json)

        [{
          "id": 1, 
          "description": "Get down on knees and pray!",
          "managerId": 1,
          "ownerId": 2,
          "deadline": "2013-12-21",
          "status": 1
        }, {
          "id": 2, 
          "description": "Save small octopuses", 
          "managerId": 0,
          "ownerId": 1,
          "deadline": "2013-12-07",
          "status": 2
        }]

### Create a Task [POST]
+ Request (application/json)

        { 
        "description": "Feed Sir Octopus.",
        "ownerId": 2,
        "managerId": 0,
        "deadline": "2013-11-30",
        "status": "opened"
        }

+ Response 201 (application/json)

        { 
        "id": 3,
        "name": "Feed Sir Octopus",
        "ownerId": 2,
        "managerId": 0,
        "deadline": "2013-11-30",
        "status": "opened"
        }

## Task [/tasks/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Task

### Update a Task [PUT]
+ Request (application/json)

        { 
        "description": "Feed Sir Octopus!",
        "ownerId": 2,
        "managerId": 0,
        "deadline": "2013-12-30",
        "status": "opened"
        }

+ Response 200 (application/json)

        { 
        "id": 3, 
        "description": "Feed Sir Octopus!",
        "ownerId": 2,
        "managerId": 0,
        "deadline": "2013-12-30",
        "status": "opened"
        }

### Remove a Task [DELETE]
+ Response 204

## Users [/users]
### Create a User [POST]
+ Request (application/json)

        { 
        "name": "Sir",
        "surname": "Octopus",
        "manager": 1,
        "username": "octopuss",
        "password": "fcf1eed8596699624167416a1e7e122e"
        }

+ Response 201 (application/json)

        { 
        "id": 1,
        "name": "Sir",
        "surname": "Octopus",
        "manager": 1,
        "username": "octopuss",
        "password": "fcf1eed8596699624167416a1e7e122e"
        }
 
## User [/users/{id}]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User
 
### Retrive a User [GET]       
+ Response 200 (application/json)

    + Body

            { 
            "id": 1,
            "name": "Sir",
            "surname": "Octopus",
            "manager": 1,
            "username": "octopuss",
            "password": "fcf1eed8596699624167416a1e7e122e"
            }