FORMAT: 1A
HOST: TODO

# Sir Octopus API
API specification used for communication between server and Android client.

## Tasks [/tasks]
### List all Tasks [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "text": "Pray for Sir Octopus"
        }, {
          "id": 2, "text": "Save small octopuses"
        }]

### Create a Task [POST]
+ Request (application/json)

        { "text": "Feed Sir Octopus" }

+ Response 201 (application/json)

        { "id": 3, "text": "Feed Sir Octopus" }

## Task [/tasks/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Task

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Body

            { "id": 3, "title": "Feed Sir Octopus" }

### Update a Task [PUT]
+ Request (application/json)

        { "text": "Feed Sir Octopus!" }

+ Response 201 (application/json)

        { "id": 3, "text": "Feed Sir Octopus!" }

### Remove a Task [DELETE]
+ Response 204
